REFRESH MATERIALIZED VIEW CONCURRENTLY organizations;
ANALYSE organizations;

REFRESH MATERIALIZED VIEW CONCURRENTLY organization_activity;
ANALYSE organization_activity;

REFRESH MATERIALIZED VIEW CONCURRENTLY authority;
ANALYSE authority;

REFRESH MATERIALIZED VIEW CONCURRENTLY authority_activity;
ANALYSE authority_activity;
