REFRESH MATERIALIZED VIEW CONCURRENTLY organizations;
ANALYSE organizations;

REFRESH MATERIALIZED VIEW CONCURRENTLY organization_activity;
ANALYSE organization_activity;

REFRESH MATERIALIZED VIEW CONCURRENTLY lms_events;
ANALYSE lms_events;
